parser: "@typescript-eslint/parser"
plugins:
  - react
  - "@typescript-eslint"
  - prettier
  - "no-only-tests"
  - "require-extensions"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "plugin:require-extensions/recommended"
overrides:
  - files:
      - "test/**/*.ts"
    rules:
      "@typescript-eslint/no-explicit-any": 0
      "no-only-tests/no-only-tests": "error"
env:
  node: true
  jest: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
